[package]
name = "{{core_name_dashes}}"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "{{core_name}}"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core = "0.7"
serde = { workspace = true, features = ["derive"] }
lazy_static = "1.4.0"
uniffi = "0.25.3"
wasm-bindgen = "0.2.89"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "0.25.3", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.25.3", features = ["build"] }
